version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
  
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run api/web_ui.py
    environment:
      - PYTHONPATH=/app
    depends_on:
      - api
